complexity:
  LongParameterList:
    active: true
    ignoreAnnotated: [ 'Composable' ]

naming:
  FunctionNaming:
    active: true
    ignoreAnnotated: [ 'Composable' ]

style:
  UnusedPrivateMember:
    active: true
    ignoreAnnotated: [ 'Preview' ]