name: Main CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build with Gradle
        run: ./gradlew assembleRelease
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: APK
          path: app/build/outputs/apk/release/app-release-unsigned.apk

  code-check:
    name: Code Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Clean
        run: ./gradlew clean
      - name: Run Detekt
        run: ./gradlew detekt
      - name: Run Ktlint
        run: ./gradlew ktlintCheck
      - name: Run Lint
        run: ./gradlew lintDebug

  code-coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Kover Verify
        run: ./gradlew koverVerify
      - name: Upload Test Report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: Test Report
          path: core/build/reports/tests/testDebugUnitTest
      - name: Run Kover Report
        run: ./gradlew koverXmlReport
      - name: Upload coverage reports
        uses: codecov/codecov-action@v2
        with:
          files: core/build/reports/kover/project-xml/report.xml