name: Main CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      ## Step 1
      - name: Checkout
        uses: actions/checkout@v2
      ## Step 2
      - name: Build with Gradle
        run: ./gradlew assembleRelease
      ## Step 3
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: APK
          path: app/build/outputs/apk/release/app-release-unsigned.apk

  code-check:
    name: Code Check
    runs-on: ubuntu-latest
    steps:
      ## Step 1
      - name: Checkout
        uses: actions/checkout@v2
      ## Step 2
      - name: Run Clean
        run: ./gradlew clean
      ## Step 3
      - name: Run Detekt
        run: ./gradlew detekt
      ## Step 4
      - name: Run Ktlint
        run: ./gradlew ktlintCheck
      ## Step 5
      - name: Run Lint
        run: ./gradlew lintDebug

  code-coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    steps:
      ## Step 1
      - name: Checkout
        uses: actions/checkout@v2
      ## Step 2
      - name: Set up Java 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      ## Step 3
      - name: Run Kover Verify
        run: ./gradlew koverVerify
      ## Step 4
      - name: Upload Test Report
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: Test Report
          path: transaction/build/reports/tests/testDebugUnitTest
      ## Step 5
      - name: Run Kover Report
        run: ./gradlew koverXmlReport
      ## Step 6
      - name: Upload coverage reports
        uses: codecov/codecov-action@v2
        with:
          files: "**/build/reports/kover/project-xml/report.xml"